version: '3.7'

services:
  detector-db:
    container_name: detector-db
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: metal-detector
      PGDATA: /var/lib/postgresql/data/db-files/
    networks:
      - detector-network
    volumes:
      - type: volume
        source: detector-db-volume
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  butler-db:
    container_name: detector-butler-db
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: metal-release-butler
      PGDATA: /var/lib/postgresql/data/db-files/
    networks:
      - butler-network
    volumes:
      - type: volume
        source: butler-db-volume
        target: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  butler-app:
    container_name: butler-app
    image: metaldetector/metal-release-butler:20220503T163818
    environment:
      DATASOURCE_URL: jdbc:postgresql://butler-db:5432/metal-release-butler
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: secret
    networks:
      - butler-network
      - service-network
    volumes:
      - type: volume
        source: butler-image-volume
        target: /app/images
      - type: volume
        source: butler-logs-volume
        target: /app/logs
    ports:
      - "8095:8080"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  auth-db:
    container_name: detector-auth-db
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: metal-detector-auth
      PGDATA: /var/lib/postgresql/data/db-files/
    networks:
      - auth-network
    volumes:
      - type: volume
        source: auth-db-volume
        target: /var/lib/postgresql/data
    ports:
      - "5434:5432"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  auth-app:
    container_name: detector-auth-app
    image: metaldetector/metal-detector-auth:20220430T071304
    environment:
      SERVER_PORT: 9000
      DATASOURCE_URL: jdbc:postgresql://auth-db:5432/metal-detector-auth
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: secret
      AUTHORIZATION_SERVER_PRIVATE_KEY:
      AUTHORIZATION_SERVER_PUBLIC_KEY:
      METAL_DETECTOR_USER_CLIENT_ID: metal-detector-user
      METAL_DETECTOR_USER_CLIENT_SECRET: userSecret
      METAL_DETECTOR_ADMIN_CLIENT_ID: metal-detector-admin
      METAL_DETECTOR_ADMIN_CLIENT_SECRET: adminSecret
      IMPORT_JOB_CLIENT_ID: import-job
      IMPORT_JOB_CLIENT_SECRET: importJobSecret
    networks:
      - auth-network
      - service-network
    ports:
      - "9000:9000"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  detector-db-volume:
    name: detector-db
  butler-db-volume:
    name: detector-butler-db
  butler-image-volume:
    name: detector-butler-images
  butler-logs-volume:
    name: detector-butler-logs
  auth-db-volume:
    name: detector-auth-db

networks:
  detector-network:
    name: detector-network
  butler-network:
    name: butler-network
  auth-network:
    name: auth-network
  service-network:
    name: service-network
