[versions]
apacheCommonsLang3 = "3.12.0"
apacheCommonsText = "1.9"
cacheApi = "1.1.1"
commonsCodec = "1.15"
datatables = "1.10.25"
ehcache = "3.9.4"
esapi = "2.2.3.1"
flyway = "7.14.1"
h2 = "1.4.200"
httpClient = "4.5.13"
jackson = "2.12.4"
jacoco = "0.8.7"
jaxbApi = "2.3.1"
jsonwebtoken = "0.9.1"
jsoup = "1.14.2"
junit = "5.8.1"
lombok = "1.18.20"
micrometer = "1.7.4"
mockito = "4.0.0"
modelmapper = "2.4.4"
postgresql = "42.2.23"
restAssured = "4.4.0"
servletApi = "4.0.1"
slf4jMock = "2.1.1"
spring = "5.3.10"
springBoot = "2.5.5"
springSecurity = "5.5.2"
thymeleafDialect = "3.0.0"
thymeleafExtras = "3.0.4.RELEASE"
