[versions]
cacheApi = "1.1.1"
commonsCodec = "1.15"
commonsLang3 = "3.12.0"
commonsText = "1.9"
datatables = "1.13.2"
ehcache = "3.10.8"
esapi = "2.5.1.0"
jacoco = "0.8.8"
jsonwebtoken = "0.9.1"
jsoup = "1.15.4"
lombok = "1.18.26"
postgresql = "42.5.4"
restAssured = "5.3.0"
servletApi = "4.0.1"
slf4jTest = "2.8.1"
thymeleafDialect = "3.2.0"
thymeleafExtras = "3.1.1.RELEASE"
