[versions]
cacheApi = "1.1.1"
commonsCodec = "1.15"
commonsLang3 = "3.12.0"
commonsText = "1.9"
datatables = "1.11.4"
ehcache = "3.10.0"
esapi = "2.4.0.0"
flyway = "8.5.11"
h2 = "2.1.212"
httpClient = "4.5.13"
jackson = "2.13.3"
jacoco = "0.8.8"
jsonwebtoken = "0.9.1"
jsoup = "1.15.1"
junit = "5.8.2"
lombok = "1.18.24"
micrometer = "1.9.0"
mockito = "4.5.1"
postgresql = "42.3.5"
restAssured = "4.5.1"
servletApi = "4.0.1"
slf4jMock = "2.2.0"
spring = "5.3.20"
springBoot = "2.7.0"
springSecurity = "5.7.0"
thymeleafDialect = "3.0.0"
thymeleafExtras = "3.0.4.RELEASE"
