[versions]
cacheApi = "1.1.1"
commonsCodec = "1.15"
commonsLang3 = "3.12.0"
commonsText = "1.9"
datatables = "1.11.3"
ehcache = "3.9.8"
esapi = "2.2.3.1"
flyway = "8.3.0"
h2 = "1.4.200"
httpClient = "4.5.13"
jackson = "2.13.1"
jacoco = "0.8.7"
jaxbApi = "2.3.1"
jsonwebtoken = "0.9.1"
jsoup = "1.14.3"
junit = "5.8.2"
lombok = "1.18.22"
micrometer = "1.8.1"
mockito = "4.2.0"
modelmapper = "2.4.5"
postgresql = "42.3.1"
restAssured = "4.4.0"
servletApi = "4.0.1"
slf4jMock = "2.1.1"
spring = "5.3.14"
springBoot = "2.6.2"
springSecurity = "5.6.1"
thymeleafDialect = "3.0.0"
thymeleafExtras = "3.0.4.RELEASE"
