[versions]
cacheApi = "1.1.1"
commonsCodec = "1.15"
commonsLang3 = "3.12.0"
commonsText = "1.9"
datatables = "1.11.4"
ehcache = "3.10.0"
esapi = "2.5.0.0"
flyway = "8.5.13"
h2 = "2.1.214"
httpClient = "4.5.13"
jackson = "2.13.3"
jacoco = "0.8.8"
jsonwebtoken = "0.9.1"
jsoup = "1.15.2"
junit = "5.9.0"
lombok = "1.18.24"
micrometer = "1.9.3"
mockito = "4.6.1"
postgresql = "42.5.0"
restAssured = "5.1.1"
servletApi = "4.0.1"
slf4jTest = "2.6.1"
thymeleafDialect = "3.1.0"
thymeleafExtras = "3.0.4.RELEASE"
