[versions]
cacheApi = "1.1.1"
commonsCodec = "1.16.0"
commonsLang3 = "3.14.0"
commonsText = "1.11.0"
datatables = "1.13.2"
ehcache = "3.10.8"
esapi = "2.5.3.1"
jsonwebtoken = "0.9.1"
jsoup = "1.17.2"
lokiLogbackAppender = "1.4.0"
lombok = "1.18.30"
postgresql = "42.7.1"
restAssured = "5.4.0"
servletApi = "4.0.1"
slf4jTest = "2.8.1"
thymeleafDialect = "3.2.0"
thymeleafExtras = "3.0.5.RELEASE" # version 3.1.x may not compatible with spring boot 2, pleas do not upgrade
