application:
  host: https://metal-detector-preview.herokuapp.com

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: true
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          spotify-app:
            redirect-uri: "https://{baseHost}{basePort}{basePath}/settings/spotify-synchronization"

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: false
  servlet:
    session:
      cookie:
        secure: true

management:
  endpoints:
    web:
      path-mapping.info: ${ACTUATOR_INFO_PATH}
      path-mapping.metrics: ${ACTUATOR_METRICS_PATH}
      path-mapping.prometheus: ${ACTUATOR_PROMETHEUS_PATH}
      path-mapping.flyway: ${ACTUATOR_FLYWAY_PATH}

metal-release-butler:
  host: https://metal-release-butler-preview.herokuapp.com
