application:
  domain: preview.metal-detector.rocks
  host: https://${application.domain}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: true
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          spotify-user:
            redirect-uri: "https://{baseHost}{basePort}{basePath}/settings/spotify-synchronization"
        provider:
          metal-detector-auth:
            issuer-uri: http://auth-app:8080

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: false
  servlet:
    session:
      cookie:
        secure: true

management:
  endpoints:
    web:
      path-mapping.info: ${ACTUATOR_INFO_PATH}
      path-mapping.metrics: ${ACTUATOR_METRICS_PATH}
      path-mapping.prometheus: ${ACTUATOR_PROMETHEUS_PATH}
      path-mapping.flyway: ${ACTUATOR_FLYWAY_PATH}

security:
  secure-cookie: true

metal-release-butler:
  host: http://butler-app:8080

frontend:
  origin: https://preview.metal-detector.rocks
