name: Compile Frontend

on:
  pull_request:
    branches:
      - master

jobs:
  compile-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # 4.2.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # 4.0.4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm --prefix webapp/src/main/resources/static/ts/ install
          npm --prefix webapp/src/main/resources/static/ts/ run compile
