name: Compile Frontend

on:
  pull_request:
    branches:
      - master

jobs:
  compile-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # 4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm --prefix webapp/src/main/resources/static/ts/ install
          npm --prefix webapp/src/main/resources/static/ts/ run compile
