name: Lint Frontend

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm --prefix webapp/src/main/resources/static/ts/ install

      - name: Run ESLint and Prettier
        run: npm --prefix webapp/src/main/resources/static/ts/ run lint
