name: Lint Frontend

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # 4.2.0
        with:
          node-version: 20

      - name: Install Corepack
        run: npm i -g corepack

      - name: Install Node.js dependencies
        run: npm --prefix webapp/src/main/resources/static/ts/ install

      - name: Run ESLint and Prettier
        run: npm --prefix webapp/src/main/resources/static/ts/ run lint
