name: Lint Frontend

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # 4.1.0
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm --prefix webapp/src/main/resources/static/ts/ install

      - name: Run ESLint and Prettier
        run: npm --prefix webapp/src/main/resources/static/ts/ run lint
