name: Update Gradle Wrapper

on:
  workflow_dispatch:
    branches:
      - master
      - preview # TODO: remove as soon as the preview branch is removed
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Set up JDK
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # 4.6.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@9268373d69bd0974b6318eb3b512b8e025060bbe # 2.0.0
        with:
          repo-token: ${{ secrets.ACTION_TOKEN }}
          labels: dependencies
          reviewers: hedgehog1833, DanielW1987
      - uses: gradle/actions/wrapper-validation@0bdd871935719febd78681f197cd39af5b6e16a6 # 4.2.2
