name: Update Gradle Wrapper

on:
  workflow_dispatch:
    branches:
      - master
      - preview # TODO: remove as soon as the preview branch is removed
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Set up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # 4.7.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@9cca748ef7cfd967bc3a5c39e15a7aa229ad1b3d # 2.0.1
        with:
          repo-token: ${{ secrets.ACTION_TOKEN }}
          labels: dependencies
          reviewers: hedgehog1833, DanielW1987
      - uses: gradle/actions/wrapper-validation@94baf225fe0a508e581a564467443d0e2379123b # 4.3.0
